version: '3'

services:

  mongo-dev:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_DATABASE=acc_system
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_mongo
    volumes:
      - ./db/mongo:/data/mongodb
    ports:
      - 27017:27017

